name: Build and Deploy to Test

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      #ff een test voor de runner
      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Build Docker images
        run: |
          docker compose down
          docker compose up --build -d
