name: Build and Deploy to Production

on:
  workflow_dispatch:

env:
  KUBECTL_VERSION: 'v1.31.2'

jobs:

  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Run tests"

  build:
    runs-on: ubuntu-24.04

    needs: [test]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy-acceptance:
    # Run in kubernetes cluster, will be changed to "production" later
    runs-on: production-runner

    needs: [build]
    
    environment:
      name: acceptance
      url: https://beta.pongello.nl/

    steps:
      - uses: azure/setup-kubectl@v4
        with:
          version: ${{ env.KUBECTL_VERSION }}
        id: install

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: Azure/k8s-create-secret@v4
        with:
           container-registry-url: ghcr.io
           container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
           container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
           secret-name: ghcr-secret

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v5
        with:
          namespace: acceptance
          manifests: |
            kubernetes/deployment.yml
          imagepullsecrets: |
              ghcr-secret


  deploy-production:
    # Run in kubernetes cluster, will be changed to "production" later
    runs-on: production-runner

    needs: [build]
    
    environment:
      name: production
      url: https://prod.pongello.nl/

    steps:
      - uses: azure/setup-kubectl@v4
        with:
          version: ${{ env.KUBECTL_VERSION }}
        id: install

      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: Azure/k8s-create-secret@v4
        with:
           container-registry-url: ghcr.io
           container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
           container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
           secret-name: ghcr-secret

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v5
        with:
          namespace: production
          manifests: |
            kubernetes/deployment.yml
          imagepullsecrets: |
              ghcr-secret
