name: Test Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Run tests"

  build:
    runs-on: ubuntu-24.04
    needs: [test]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Build PR image"